name: dmaplm

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10.16
  - numpy=1.23.1
  - scipy=1.11.3
  - pandas=2.2.3
  - scikit-learn=1.1.2
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - matplotlib=3.5.1
  - seaborn=0.12.2
  - rdkit=2024.9.6
  - tqdm=4.67.1
  - pip=25.0
  - pip:
      - transformers==4.36.0
      - tokenizers==0.15.0
      - sentencepiece==0.1.99
      - torch-geometric==2.2.0
      - torch-scatter==2.1.0
      - torch-sparse==0.6.16
      - torch-cluster==1.6.0
      - torch-spline-conv==1.2.1
